import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";

import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { useMemo } from "react";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user?.id);

  if (!user) return null;

  return (
    <div className="flex gap-3">
      <Image
        src={user.profileImageUrl}
        alt={`${user.username || ""} Profile Image`}
        className="rounded-full"
        width={56}
        height={56}
      />
      <input
        className="grow border-none bg-transparent outline-none"
        placeholder="Type some emojis"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = ({ post, author }: PostWithUser) => {
  const timePosted = useMemo(() => dayjs(post.createdAt).fromNow(), [post]);

  return (
    <div className="flex items-center gap-3 border-b border-slate-400 p-4">
      <Image
        className="w-12 rounded-full"
        src={author?.profileImageUrl}
        alt={`${author.username}'s profile picture`}
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex">
          <span className="text-slate-300">{`@${author.username}`}</span>
          &nbsp;•&nbsp;
          <span className="font-thin text-slate-400">{timePosted}</span>
        </div>
        <span className="text-slate-400">{post.content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x-2 border-slate-400 md:max-w-2xl">
          <div className="flex justify-start border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && (
              <div className="flex w-full flex-col">
                <CreatePostWizard />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {data?.map(({ post, author }) => (
              <PostView key={post.id} post={post} author={author} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
